name: Test Go application

on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build
        working-directory: .
        run:  go build -o go-todo

      - name: Run App
        working-directory: .
        run:  ./go-todo &

      - name: Wait for App to start
        run: sleep 10

      - name: Test
        run: go test ./...
